### ISSUE TITLE
Change filetype defs seem to don't have any effect

### ISSUE THREAD

**Issue by frlan** [geany/geany-osx#7] opened 2017-04-25 13:20 UTC
I've updated the filetype-defintions for python via the Tools->Configuration Files->Filetype Configuration->Scripting Languages->fileytypes.python and added 

> [indentation]
> width=4
> type=0

which should be also the default. But even after restarting Geany when opening a Python-file default indent is done via \t.  (1.30.1 on 10.11.6)

**Comment by elextr** [comment] 2017-04-25 14:14
Is it being overridden by a project?

**Comment by frlan** [comment] 2017-04-25 14:43
No, it isn't

**Comment by frlan** [comment] 2017-04-25 14:43
At least there is no open project according to the project menu.

**Comment by techee** [comment] 2017-04-25 22:05
@frlan I just tried and it works for me on Mac too. Are you sure you closed the file before retrying? (Otherwise the indentation type is stored into the session file.). Also don't you use indentation autodetection which could override it?

I don't think spaces are default for Python - the default is to use global or project settings.

That said, there really is a bug - the local filetype config file should be created based on the global one which doesn't happen now. I've just fixed it in

https://github.com/geany/geany/pull/1482

**Comment by elextr** [comment] 2017-04-26 00:41
Seems to work for me, but then I usually use spaces for everything so all my settings are `spaces` and maybe its one I forgot to change back to tabs that is making it work.

**Comment by techee** [comment] 2019-10-23 18:30
I can't reproduce the bug (or it's fixed) so closing. Feel free to reopen it if you still experience the problem.

**Closed as completed by techee** 2019-10-23 18:30 UTC
